name: Uploads Website Repo to S3 and Invalidate Cloudfront Distribution cache

on:
  push:
    branches:
    - main

jobs: 
  upload-website-repo-to-s3:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@master
        
        - name: sync s3
          uses: jakeajarvis/s3-sync-action@master
          with: 
            args: --follow-symlinks --delete --exclude '.git/*' --size-only
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-east-1'
            SOURCE_DIR: 'website'
            
  invalidate-cloudfront-distribution-cache:  
      needs: upload-website-repo-to-s3
      runs-on: ubuntu-latest
      steps:
        - name: Invalidate CloudFront
          uses: chetan/invalidate-cloudfront-action@v2
          env:
            DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
            PATHS: "/*"
            AWS_REGION: "us-east-1"
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
